#### Лабораторная работа 1. Обращение матрицы с измененным столбцом
Реализовать алгоритм выявления и построения (если возможно) обратной матрицы по заданным данным.

$----------------------------------------------$

In [1]:
import numpy as np

<u>Шаг 0.</u> Ввод входных данных: матрица $A$ (и её размер $ n $), обратная ей матрица $A^{-1}$, вектор $\vec{x}$ и позиция <i>i</i>.

In [2]:
a = np.array([[1, -9, 35], [9, 1, 4], [6, 56, 3]]) 
a_invert = np.linalg.inv(a)
x_vect = np.array([75, 664, 34])
i = 3
n = 3

print("A =", a, "\n\nA_invert =", a_invert, "\n\nx_vect =", x_vect, "\n\ni =", i, "\n\nn =", n)

A = [[ 1 -9 35]
 [ 9  1  4]
 [ 6 56  3]] 

A_invert = [[-0.012822    0.11528197 -0.00411929]
 [-0.00017405 -0.01200975  0.01804363]
 [ 0.02889301 -0.00638199  0.00475748]] 

x_vect = [ 75 664  34] 

i = 3 

n = 3


Тогда матрица $\overline{A}$ будет выглядеть следующим образом:

In [3]:
a_wrk = a

for counter in range(0, n):
    a_wrk[counter][i - 1] = x_vect[counter]

print(a_wrk)

[[  1  -9  75]
 [  9   1 664]
 [  6  56  34]]


<u>Шаг 1.</u> Находим ℓ = $ A^{-1}x $. Если $ ℓ_{i} $ = 0, то матрица $\overline{A}$ необратима и метод завершает свою работу; в противном случае матрица $\overline{A}$ обратима и мы переходим на следующий шаг.

In [4]:
l = np.dot(a_invert, x_vect)
print("l = ", l)
if l[i - 1] == 0:
    print("Матрица A_wrk необратима")
else:
    print("Матрица A_wrk обратима")

l =  [75.445521   -7.3740427  -1.90891158]
Матрица A_wrk обратима


<u>Шаг 2.</u> Формируем вектор $ \widetilde{ℓ} $, который получается из вектора ℓ заменой $ i $-го элемента на −1.

In [5]:
l_wave = l.copy()
l_wave[i - 1] = -1
print("l_wave = ", l_wave)


l_wave =  [75.445521  -7.3740427 -1.       ]


<u>Шаг 3.</u> Находим $ \hat{ℓ} = − \frac{1}{ℓ_{i}} \widetilde{ℓ} $.

In [6]:
l_hat = ((-1)/l[i - 1]) * l_wave
print("l_hat = ", l_hat)

l_hat =  [39.52279497 -3.86295666 -0.52385873]


<u>Шаг 4.</u> Формируем матрицу $ Q $, которая получается из единичной матрицы порядка $ n $ заменой $ i $-го столбца на столбец $ \hat{ℓ} $

In [7]:
q = np.eye(n)

for count in range(0, n):
    q[count][n - 1] = l_hat[count]

print(q)

[[ 1.          0.         39.52279497]
 [ 0.          1.         -3.86295666]
 [ 0.          0.         -0.52385873]]


<u>Шаг 5.</u> Находим $ (\hat{A})^{-1} = QA^{-1} $.

In [8]:
a_result = np.zeros((n, n))

for j in range(0, n):
    for k in range(0, n):
        if i - 1 != j:
            a_result[j][k] = q[j][j] * a_invert[j][k] + q[j][i - 1] * a_invert[i - 1][k]
        else: 
            a_result[j][k] = q[j][i - 1] * a_invert[i - 1][k]

Ответ:

In [9]:
print(a_result)

[[ 1.12911069e+00 -1.36952161e-01  1.83909793e-01]
 [-1.11786518e-01  1.26436083e-02 -3.34326181e-04]
 [-1.51358580e-02  3.34326181e-03 -2.49224971e-03]]
